### ISSUE TITLE
AvoDeduplicator clearOldEvents crash

### ISSUE THREAD

**Issue by lu15gv** [avohq/ios-datascope#23]
I have several crashes in my app due to this:

![avo_crash](https://user-images.githubusercontent.com/7926457/96900305-9174e700-1457-11eb-9fce-fcfa0ae9c8d2.png)

I have not been able to reproduce it, but I see that it is a constant crash on Crashlytics.

**Comment by aleks-tpom6oh** [comment]
Thanks for reporting!

**Comment by aleks-tpom6oh** [comment]
@lu15gv please check the new version 1.2.3, should be fixed there!

**Comment by lu15gv** [comment]
@tpom6oh I'll update it, thanks!
