### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by lu15gv** [avohq/ios-datascope#26]
![Screen Shot 2020-10-30 at 17 09 53](https://user-images.githubusercontent.com/7926457/97763963-c675df00-1ad2-11eb-9199-8df233be5018.png)

![Screen Shot 2020-10-30 at 16 57 46](https://user-images.githubusercontent.com/7926457/97763467-4f8c1680-1ad1-11eb-9484-fcf116fa376c.png)

I found this memory leak during a check, it seems that is happening in inside AvoInspector pod

**Comment by aleks-tpom6oh** [comment]
Hi @lu15gv! Could you check which version of the library was used at the time of reporting? Is this still an issue?

**Comment by aleks-tpom6oh** [comment]
We've done some research and improved memory management recently. Please let us know if this happens again in version 1.2.4.
