### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by leosalmaso** [avohq/ios-datascope#29]
Hey folks, are you planning to include support for SPM? We are considering to use AVO, but that is a blocker.

Thanks!!

**Comment by aleks-tpom6oh** [comment]
Hi @leosalmaso, yes, definitely, just need someone to use it 😄 Drop us a line at hi@avo.app and we'll figure the details.

**Comment by aleks-tpom6oh** [comment]
Hey! It's available at https://github.com/avohq/ios-avo-inspector-spm
